[package]
name = "warp-gf256"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }

[[bench]]
name = "scalar_product"
harness = false

[dependencies]
thiserror = "~2"
